[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc = "0.8.9" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
# remappings = [
#     '@chainlink/=node_modules/@chainlink/',
#     '@divergencetech/=node_modules/@divergencetech/',
#     '@ensdomains/=node_modules/@ensdomains/',
#     '@openzeppelin/=node_modules/@openzeppelin/',
#     'erc721a-upgradeable/=node_modules/erc721a-upgradeable/',
#     'erc721a/=node_modules/erc721a/',
#     'eth-gas-reporter/=node_modules/eth-gas-reporter/',
#     'hardhat-deploy/=node_modules/hardhat-deploy/',
#     'hardhat/=node_modules/hardhat/',
#     'truffle/=node_modules/truffle/'
# ]

# ## set only when the `hardhat` profile is selected
# [profile.hardhat]
# src = "contracts"
# out = "artifacts"
# libs = ["node_modules"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config